# Generated by Django 3.0.5 on 2020-06-15 23:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.PositiveIntegerField(unique=True, verbose_name='Telegram user ID')),
                ('username', models.CharField(max_length=255, null=True, verbose_name='User name')),
                ('first_name', models.CharField(max_length=255, null=True, verbose_name='First name')),
                ('last_name', models.CharField(max_length=255, null=True, verbose_name='Last name')),
                ('last_activity', models.DateTimeField(null=True, verbose_name='Last activity')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Registration date')),
            ],
            options={
                'verbose_name': 'Telegram User',
            },
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('mnemonic', models.CharField(max_length=255, null=True)),
                ('private_key', models.CharField(max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wallets', to='user.TelegramUser')),
            ],
        ),
        migrations.CreateModel(
            name='VirtualWallet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(max_length=255)),
                ('balance', models.DecimalField(decimal_places=0, default=0, max_digits=40)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='virt_wallets', to='user.TelegramUser')),
            ],
        ),
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(default='ru', max_length=255)),
                ('currency', models.CharField(default='USD', max_length=255)),
                ('announcement_id', models.PositiveIntegerField(null=True)),
                ('active_deal', models.IntegerField(null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='user.TelegramUser')),
            ],
        ),
        migrations.CreateModel(
            name='UserRef',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref_created_at', models.DateTimeField(auto_now_add=True)),
                ('referrer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.TelegramUser')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ref', to='user.TelegramUser')),
            ],
        ),
        migrations.CreateModel(
            name='UserPurse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True)),
                ('currency', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255, null=True)),
                ('status', models.CharField(default='invalid', max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purse', to='user.TelegramUser')),
            ],
        ),
        migrations.CreateModel(
            name='UserMsg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trade_menu', models.PositiveIntegerField(null=True)),
                ('wallet_menu', models.PositiveIntegerField(null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='msg', to='user.TelegramUser')),
            ],
        ),
        migrations.CreateModel(
            name='UserFlag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temp_currency', models.CharField(max_length=255, null=True)),
                ('requisites_for_trade', models.BooleanField(default=False)),
                ('requisites_for_start_deal', models.BooleanField(default=False)),
                ('await_amount_for_trade', models.BooleanField(default=False)),
                ('await_currency_value', models.BooleanField(default=False)),
                ('await_amount_for_deal', models.BooleanField(default=False)),
                ('await_requisites_address', models.BooleanField(default=False)),
                ('await_requisites_name', models.BooleanField(default=False)),
                ('edit_requisite', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flags', to='user.TelegramUser')),
            ],
        ),
    ]
