# Generated by Django 3.0.5 on 2020-06-16 02:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20200616_0454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpurse',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requisites', to='user.TelegramUser'),
        ),
    ]
