# Generated by Django 3.0.5 on 2020-06-16 03:37

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20200616_0506'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramuser',
            name='cache',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={'clipboard': {'active_trade': None, 'currency': None}, 'msg': {'trade_menu': None, 'wallet_menu': None}}),
        ),
        migrations.AddField(
            model_name='userflag',
            name='await_requisites_for_order',
            field=models.BooleanField(default=False),
        ),
    ]
