# Generated by Django 3.0.5 on 2020-06-18 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_userflag_await_currency_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='userflag',
            name='await_amount_for_order',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userflag',
            name='await_requisite_for_order',
            field=models.BooleanField(default=False),
        ),
    ]
