# Generated by Django 3.0.5 on 2020-06-20 01:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_auto_20200618_0447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='virtualwallet',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='virtual_wallets', to='user.TelegramUser'),
        ),
    ]
