# Generated by Django 3.0.5 on 2020-07-01 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade',
            name='status',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
