# Generated by Django 3.0.5 on 2020-07-01 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0002_auto_20200701_0432'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trade',
            name='deposite',
        ),
        migrations.AddField(
            model_name='trade',
            name='type_trade',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
