# Generated by Django 3.0.5 on 2020-07-03 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0003_auto_20200701_0437'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='price_trade',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=40),
        ),
    ]
