# Generated by Django 3.0.5 on 2020-07-03 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0004_trade_price_trade'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='tx_hash',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
