# Generated by Django 3.0.5 on 2020-07-11 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0007_trade_trade_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade',
            name='trade_currency',
            field=models.CharField(max_length=255),
        ),
    ]
