# Generated by Django 3.0.5 on 2020-07-20 00:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0009_auto_20200718_0420'),
    ]

    operations = [
        migrations.CreateModel(
            name='TradeHoldMoney',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=0, default=0, max_digits=40)),
                ('trade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holdMoney', to='trade.Trade')),
            ],
        ),
        migrations.DeleteModel(
            name='HoldMoney',
        ),
    ]
