# Generated by Django 3.0.5 on 2020-08-29 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0010_auto_20200720_0351'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='fee',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=40),
        ),
    ]
