# Generated by Django 3.0.5 on 2020-08-29 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0011_trade_fee'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trade',
            old_name='fee',
            new_name='maker_fee',
        ),
        migrations.AddField(
            model_name='trade',
            name='taker_fee',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=40),
        ),
    ]
