# Generated by Django 3.0.5 on 2020-06-12 18:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('order', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=255)),
                ('payment_currency', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=0, default=0, max_digits=40)),
                ('deposite', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.Order')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trade', to='user.User')),
            ],
        ),
        migrations.CreateModel(
            name='HoldMoney',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=0, default=0, max_digits=40)),
                ('trade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trade.Trade')),
            ],
        ),
    ]
