# Generated by Django 3.0.5 on 2020-07-11 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0005_trade_tx_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='payment_currency_rate',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=40),
        ),
        migrations.AddField(
            model_name='trade',
            name='trade_currency_rate',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=40),
        ),
    ]
