# Generated by Django 3.0.5 on 2020-07-03 16:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0015_userflag_await_tx_hash'),
        ('bot', '0003_auto_20200703_1800'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashflow',
            name='to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='_cashflow', to='user.TelegramUser'),
        ),
        migrations.AlterField(
            model_name='cashflow',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cashflow', to='user.TelegramUser'),
        ),
    ]
