# Generated by Django 3.0.5 on 2020-07-12 09:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0008_auto_20200711_0443'),
        ('bot', '0004_auto_20200703_1919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashflow',
            name='trade',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='trade.Trade'),
        ),
    ]
