# Generated by Django 3.0.5 on 2020-07-23 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0007_settings'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrencyList',
            fields=[
                ('currency', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=25)),
                ('accuracy', models.PositiveIntegerField()),
            ],
        ),
    ]
