# Generated by Django 3.0.5 on 2020-08-10 02:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0020_userflag_await_amount_for_withdrawal'),
        ('bot', '0008_currencylist'),
    ]

    operations = [
        migrations.CreateModel(
            name='WithdrawalRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(max_length=25)),
                ('amount', models.DecimalField(decimal_places=0, max_digits=40)),
                ('address', models.CharField(max_length=250)),
                ('fee', models.DecimalField(decimal_places=0, max_digits=40)),
                ('network_fee', models.DecimalField(decimal_places=0, max_digits=40, null=True)),
                ('tx_hash', models.CharField(max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='pending verification', max_length=255)),
                ('type_withdrawal', models.CharField(max_length=250, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='withdrawalRequests', to='user.TelegramUser')),
            ],
        ),
    ]
