# Generated by Django 3.0.5 on 2020-06-16 00:08

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temporder',
            name='payment_currency',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50, unique=True), default=list, size=10),
        ),
    ]
