# Generated by Django 3.0.5 on 2020-06-16 03:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_auto_20200616_0331'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='temporder',
            managers=[
            ],
        ),
    ]
