# Generated by Django 3.0.5 on 2020-06-21 21:26

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_auto_20200618_0633'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderMirror',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_operation', models.CharField(max_length=255)),
                ('trade_currency', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=0, max_digits=40)),
                ('currency_rate', models.DecimalField(decimal_places=0, max_digits=40)),
                ('payment_currency', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
                ('requisites', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(max_length=255)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mirror', to='order.Order')),
            ],
        ),
    ]
