# Generated by Django 3.0.5 on 2020-06-28 00:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0011_auto_20200628_0315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='parent_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.ParentOrder'),
        ),
    ]
