# Generated by Django 3.0.5 on 2020-07-09 01:18

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0014_order_payment_currency_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='temporder',
            name='payment_currency_rate',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
    ]
