# Generated by Django 3.0.5 on 2020-07-09 03:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0016_auto_20200709_0427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='parent_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='order.ParentOrder'),
        ),
    ]
