# Generated by Django 3.0.5 on 2020-07-03 04:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0015_userflag_await_tx_hash'),
        ('trade', '0004_trade_price_trade'),
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CashFlowStatement',
            new_name='CashFlow',
        ),
    ]
