# Generated by Django 3.0.5 on 2020-07-03 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_auto_20200703_0729'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cashflow',
            name='fee_currency',
        ),
        migrations.RemoveField(
            model_name='cashflow',
            name='tx_fee',
        ),
    ]
