"""
Django settings for trader_bot project.

Generated by 'django-admin startproject' using Django 3.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/3.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.0/ref/settings/
"""
import os
from _decimal import Decimal
from collections import OrderedDict

from .env import env

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env.str('SECRET_KEY', default='qwerty')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env.bool('DEBUG', default=False)

ALLOWED_HOSTS = [
    "127.0.0.1",
    "localhost",
]

# Application definition

INSTALLED_APPS = [
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'modeltranslation',
    'django.contrib.admin',
    'constance',
    'constance.backends.database',
    'django_apscheduler',
    'bot',
    'user',
    'order',
    'trade',
    'silk',
]

APSCHEDULER_DATETIME_FORMAT = "N j, Y, f:s a"

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'silk.middleware.SilkyMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'

# Database
# https://docs.djangoproject.com/en/3.0/ref/settings/#databases


DATABASES = {
    'default': env.db('DATABASE_URL')
}

CONSTANCE_BACKEND = 'constance.backends.database.DatabaseBackend'
CONSTANCE_DATABASE_PREFIX = 'constance:trader-bot:'

# CACHES = {
#     'default': {
#         'BACKEND': 'django.core.cache.backends.memcached.MemcachedCache',
#         'LOCATION': '127.0.0.1:11211',
#     }
# }
# CONSTANCE_DATABASE_CACHE_BACKEND = 'default'

CONSTANCE_CONFIG = OrderedDict(
    [
        ('CRON_CHECK_REFILL_BIP_SEC', (5, 'Интервал запуска джобы пополнения BIP')),
        ('CRON_CHECK_REFILL_ETH_SEC', (20, 'Интервал запуска джобы пополнения ETH')),
        ('CRON_CHECK_REFILL_BTC_SEC', (60, 'Интервал запуска джобы пополнения BTC')),
        ('CRON_UPDATE_EXCHANGE_RATES_MIN', (20, 'Интервал запуска джобы парса курса валют')),
        ('CRON_VERIFICATION_WITHDRAWAL_REQUESTS_SEC', (10, 'Интервал запуска джобы проверки заявок на вывод средств')),
        ('CRON_CHECK_SUBSCRIPTION_TIME_SEC', (300, 'Интервал проверки времени реф подписки')),
        ('ETH_NODE', ('http://isheldon:dfhjgkjnlkdrlRHJYrstdryS346645346ythdfshyfHEr4635763Y4hbfGSDs@116.202.202.230/dsfkhkgdl/', ' ')),
        ('MINTER_NODE', ('http://195.201.211.234:8841', ' ')),
        ('BTC_NODE', ('http://{user}:{password}@195.201.211.234:8878', ' ')),
        ('BTC_WALLET_NAME', ('garry', 'Имя основного глобального кошелька, по умолчанию установлено имя dev кошелька')),
        ('GET_MAX_PRICE_RANGE_FACTOR', (Decimal('1'), 'Коэффициент максимального отклонения от курса валют')),
        ('WITHDRAWAL_FACTOR', (Decimal('1.2'), 'некий коэффициент для вычисления максимальной суммы вывода')),
        ('TAKER_FEE', (Decimal('0.3'), 'Юзер который отозвался на объявление')),
        ('MAKER_FEE', (Decimal('0.3'), 'Создатель объявления')),
        ('AFFILIATE_FEE', (Decimal('0.25'), 'Комса рефереру')),
        ('MIN_AMOUNT_CONVERT_BONUS', (1, 'Минимальная сумма для конвертации бонусных шекелей')),
        ('', ('', '')),
    ]
)

# CONSTANCE_CONFIG =

# Password validation
# https://docs.djangoproject.com/en/3.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/3.0/topics/i18n/
# LANGUAGE_CODE = 'ru-ru'
LANGUAGE_CODE = 'en-us'

gettext = lambda s: s
LANGUAGES = [
    ('ru', 'Russian'),
    ('en', 'English'),
]

MODELTRANSLATION_TRANSLATION_REGISTRY = 'bot.translation'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.0/howto/static-files/
_SETTINGS_DIR = os.path.dirname(os.path.abspath(__file__))
_CONFIG_DIR = os.path.dirname(_SETTINGS_DIR)
PROJECT_DIR = os.path.dirname(_CONFIG_DIR)
STATIC_ROOT = os.path.join(PROJECT_DIR, 'static')
STATIC_URL = '/static/'
