# Generated by Django 3.0.5 on 2020-06-16 14:52

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20200616_0637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramuser',
            name='cache',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={'clipboard': {'active_trade': None, 'currency': None, 'requisites': list}, 'msg': {'trade_menu': None, 'wallet_menu': None}}),
        ),
    ]
