# Generated by Django 3.0.5 on 2020-06-17 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_auto_20200616_1752'),
    ]

    operations = [
        migrations.AddField(
            model_name='userflag',
            name='await_currency_rate',
            field=models.BooleanField(default=False),
        ),
    ]
