# Generated by Django 3.0.5 on 2020-07-02 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_auto_20200629_2111'),
    ]

    operations = [
        migrations.AddField(
            model_name='userflag',
            name='await_tx_hash',
            field=models.BooleanField(default=False),
        ),
    ]
