# Generated by Django 3.0.5 on 2020-07-12 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0015_userflag_await_tx_hash'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='telegramuser',
            name='cache',
        ),
    ]
