# Generated by Django 3.0.5 on 2020-07-20 03:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0016_auto_20200712_2003'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userflag',
            name='await_amount_for_deal',
        ),
        migrations.RemoveField(
            model_name='userflag',
            name='await_currency_value',
        ),
        migrations.RemoveField(
            model_name='userflag',
            name='requisites_for_start_deal',
        ),
        migrations.RemoveField(
            model_name='userflag',
            name='temp_currency',
        ),
    ]
