# Generated by Django 3.0.5 on 2020-07-20 03:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0017_auto_20200720_0627'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userflag',
            name='requisites_for_trade',
        ),
    ]
