# Generated by Django 3.0.5 on 2020-07-28 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0018_remove_userflag_requisites_for_trade'),
    ]

    operations = [
        migrations.AddField(
            model_name='userflag',
            name='await_replenishment_for_order',
            field=models.BooleanField(default=False),
        ),
    ]
