# Generated by Django 3.0.5 on 2020-08-09 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0019_userflag_await_replenishment_for_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='userflag',
            name='await_amount_for_withdrawal',
            field=models.BooleanField(default=False),
        ),
    ]
