# Generated by Django 3.0.5 on 2020-08-11 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0020_userflag_await_amount_for_withdrawal'),
    ]

    operations = [
        migrations.AddField(
            model_name='userflag',
            name='await_tx_hash_for_withdrawal',
            field=models.BooleanField(default=False),
        ),
    ]
