# Generated by Django 3.0.5 on 2020-08-26 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0021_userflag_await_tx_hash_for_withdrawal'),
    ]

    operations = [
        migrations.AddField(
            model_name='userflag',
            name='await_replenishment_for_trade',
            field=models.BooleanField(default=False),
        ),
    ]
