# Generated by Django 3.0.5 on 2020-08-31 02:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0023_userflag_in_trade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userref',
            name='referrer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Ref', to='user.TelegramUser'),
        ),
    ]
