# Generated by Django 3.0.5 on 2020-09-01 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0024_auto_20200831_0509'),
    ]

    operations = [
        migrations.AddField(
            model_name='userflag',
            name='await_amount_for_convert_bonus',
            field=models.BooleanField(default=False),
        ),
    ]
