# Generated by Django 3.0.5 on 2020-06-18 03:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_auto_20200617_0423'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='order',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='temporder',
            name='max_limit',
        ),
        migrations.RemoveField(
            model_name='temporder',
            name='min_limit',
        ),
    ]
