# Generated by Django 3.0.5 on 2020-06-26 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0009_order_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='temporder',
            name='status',
            field=models.CharField(default='close', max_length=255),
        ),
    ]
