# Generated by Django 3.0.5 on 2020-06-28 00:15

import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_auto_20200621_0331'),
        ('order', '0010_temporder_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='order',
            name='order_id',
        ),
        migrations.RemoveField(
            model_name='order',
            name='user',
        ),
        migrations.RemoveField(
            model_name='temporder',
            name='order_id',
        ),
        migrations.CreateModel(
            name='ParentOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.UUIDField(default=uuid.uuid4)),
                ('type_operation', models.CharField(max_length=255, null=True)),
                ('trade_currency', models.CharField(max_length=255, null=True)),
                ('amount', models.DecimalField(decimal_places=0, max_digits=40)),
                ('currency_rate', models.DecimalField(decimal_places=0, max_digits=40, null=True)),
                ('payment_currency', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), default=list, size=10)),
                ('requisites', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
                ('status', models.CharField(default='close', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_orders', to='user.TelegramUser')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='parent_order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='order.ParentOrder'),
        ),
    ]
