# Generated by Django 3.0.5 on 2020-06-28 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0012_auto_20200628_0315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(default='close', max_length=255),
        ),
    ]
