# Generated by Django 3.0.5 on 2020-07-09 01:27

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0015_temporder_payment_currency_rate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='payment_currency_rate',
        ),
        migrations.AddField(
            model_name='parentorder',
            name='payment_currency_rate',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
    ]
