# Generated by Django 3.0.5 on 2020-07-16 23:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0017_auto_20200709_0618'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderHoldMoney',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=0, max_digits=40)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holdMoney', to='order.ParentOrder')),
            ],
        ),
    ]
