# Generated by Django 3.0.5 on 2020-07-22 17:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0018_remove_userflag_requisites_for_trade'),
        ('order', '0018_orderholdmoney'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parentorder',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parentOrders', to='user.TelegramUser'),
        ),
    ]
