# Generated by Django 3.0.5 on 2020-07-24 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0019_auto_20200722_2003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(default='open', max_length=255),
        ),
        migrations.AlterField(
            model_name='parentorder',
            name='status',
            field=models.CharField(default='open', max_length=255),
        ),
    ]
