# Generated by Django 3.0.5 on 2020-07-27 01:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0018_remove_userflag_requisites_for_trade'),
        ('order', '0022_auto_20200727_0339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderholdmoney',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holdMoney', to='user.TelegramUser'),
        ),
    ]
