# Generated by Django 3.0.5 on 2020-08-29 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0023_auto_20200727_0400'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderholdmoney',
            name='fee',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=40),
        ),
    ]
