# Generated by Django 3.0.5 on 2020-10-01 00:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0025_auto_20200829_0415'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderholdmoney',
            name='fee',
        ),
    ]
