# Generated by Django 3.0.5 on 2020-11-29 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0027_order_order_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order_id',
        ),
    ]
